[package]
name = "consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
rdkafka = { version = "0.38", features = ["cmake-build"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"